name: Despliegue de APPWEB a EC2

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notificación de éxito
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_SMTP_HOST }}
          server_port: ${{ secrets.EMAIL_SMTP_PORT }}
          username: ${{ secrets.EMAIL_SMTP_USER }}
          password: ${{ secrets.EMAIL_SMTP_PASSWORD }}
          subject: "Deploy exitoso: ${{ github.workflow }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_SMTP_USER }}
          content_type: text/html
          html_body: |
            <h2 style="color:green;">Deploy exitoso</h2>
